### ISSUE TITLE
Fix warning: 'sakeapp': dependency 'swiftshell' is not used by any target

### ISSUE THREAD

**Issue by kabirkhaan** [kattouf/Sake#20]
Hello, I am trying to run [advanced-cli-tools-running](https://sakeswift.org/advanced-cli-tools-running.html)

After adding the `SwiftShell` when I run `sake list` or `any sake command` I am getting the following error
```swift
 1 | import Foundation
 2 | import Sake
 3 | import SwiftShell
   |        `- error: no such module 'SwiftShell'
 4 |
 5 | @CommandGroup
```

Sample example code.
```swift
import Foundation
import Sake
import SwiftShell

@main
@CommandGroup
struct Commands: SakeApp {
    public static var build: Command {
        Command(
            description: "Build the project using a shell command"
        ) { context in
            try runAndPrint("swift", "build")
        }
    }
}
```

After opening a `Package.swift` I get the following  warning
<img width="566" alt="Screenshot 2024-12-13 at 16 14 32" src="https://github.com/user-attachments/assets/f48f0172-b677-43f7-b275-3b3e394b223a" />

Then I open the `package.swift` and the `SwiftShell ` under the `targets. dependencies `.  

```swift
// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import CompilerPluginSupport
import PackageDescription

let package = Package(
    name: "SakeApp",
    platforms: [.macOS(.v10_15)], // Required by SwiftSyntax for the macro feature in Sake
    products: [
        .executable(name: "SakeApp", targets: ["SakeApp"]),
    ],
    dependencies: [
        .package(url: "https://github.com/kattouf/Sake", from: "0.1.0"),
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.2.0"),
        .package(url: "https://github.com/kareman/SwiftShell", from: "5.1.0")
    ],
    targets: [
        .executableTarget(
            name: "SakeApp",
            dependencies: [
                "Sake",
                "SwiftShell" // Needs to add this line 
            ],
            path: "."
        ),
    ]
)

```

After this steps, I am able to run the sake app again.

Would it be possible to add this in step the mentioned tutorial [advanced-cli-tools-running](https://sakeswift.org/advanced-cli-tools-running.html)?

**Comment by kattouf** [comment]
Thank you for your attention to detail, I’ll review everything and fix the issues you pointed out.

By the way, if you’re interested in more complex examples, you can also take a look at how `Sake` is used in the `Sake` repository itself: https://github.com/kattouf/Sake/tree/main/SakeApp
