### ISSUE TITLE
Suggestion: Update documenation w.r.t mise.toml file 

### ISSUE THREAD

**Issue by kabirkhaan** [kattouf/Sake#21]
In the installation [page](https://sakeswift.org/installation.html)  following is the step for `Mise`

<img width="736" alt="Screenshot 2024-12-13 at 16 33 50" src="https://github.com/user-attachments/assets/4757ba1f-ff4d-4589-b785-ec141c319b5d" />

Suggestion it would be great if we add how to add this in `mise.toml ` example 

In our case, we are using `mise.toml` file and I have to add the following 
```
[alias]
"spm:kattouf/Sake" = "0.2.3"
```

If we add this in documentation it will be helpful for other developers.

Thanks

**Comment by kattouf** [comment]
That’s a great suggestion, thank you for sharing.
By the way, I thought that Sake could also potentially be installed through a [UBI](https://mise.jdx.dev/dev-tools/backends/ubi.html) backend. I’ll check this separately and add it if possible.

**Comment by kabirkhaan** [comment]
That would be awesome 🤩

**Comment by kattouf** [comment]
I’ve added information about the mise.toml config, but I need to test some changes to ensure it works with UBI after publishing the new release
